// Generates src/data/cocBuildingIds.ts — the dataId → name mapping used to
// decode a Clash of Clans JSON Export snapshot. IDs come from the
// clash-of-clans-data package (same canonical source as buildingData.ts).
// Regenerate after updating clash-of-clans-data with: npm run gen:coc-ids

import { home, builder } from 'clash-of-clans-data';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outPath = join(root, 'src', 'data', 'cocBuildingIds.ts');

const collect = (items) => {
  const map = new Map();
  for (const it of items) {
    if (it.dataId != null) map.set(it.dataId, it.name);
  }
  return map;
};

const hh = home();
const bb = builder();

const homeIds = new Map();
const addHome = (items) => {
  for (const [id, name] of collect(items)) {
    if (!homeIds.has(id)) homeIds.set(id, name);
  }
};

addHome(hh.defenses().get());
addHome(hh.resourceBuildings().get());
addHome(hh.resourceBuildings().clanCastle().get());
addHome(hh.otherBuildings().helperHut().get());
addHome(hh.armyBuildings().armyCamp().get());
addHome(hh.armyBuildings().barracks().get());
addHome(hh.armyBuildings().darkBarracks().get());
addHome(hh.armyBuildings().laboratory().get());
addHome(hh.armyBuildings().spellFactory().get());
addHome(hh.armyBuildings().darkSpellFactory().get());
addHome(hh.armyBuildings().heroHall().get());
addHome(hh.armyBuildings().blacksmith().get());
addHome(hh.armyBuildings().workshop().get());
addHome(hh.armyBuildings().petHouse().get());
addHome(hh.townHall ? hh.townHall().get() : []);
addHome(hh.traps().get());
addHome(hh.walls().get());

const builderIds = new Map();
const addBuilder = (items) => {
  for (const [id, name] of collect(items)) {
    if (!builderIds.has(id)) builderIds.set(id, name);
  }
};
addBuilder(bb.defenses().get());
addBuilder(bb.resourceBuildings().get());
addBuilder(bb.armyBuildings().get());
addBuilder(bb.otherBuildings().get());
addBuilder(bb.traps().get());
addBuilder(bb.walls().get());
addBuilder(bb.builderHall().get());

const emit = (map) => {
  const sorted = [...map.entries()].sort((a, b) => a[0] - b[0]);
  return sorted
    .map(([id, name]) => `  ${id}: ${JSON.stringify(name)},`)
    .join('\n');
};

const lines = [];
lines.push('// AUTO-GENERATED by scripts/gen-coc-ids.mjs — do not edit by hand.');
lines.push('// Regenerate after updating clash-of-clans-data with: npm run gen:coc-ids');
lines.push('');
lines.push('// dataId → entity name for the Clash of Clans JSON Export format.');
lines.push('// Note: some names collide across villages (e.g. Cannon is a Home and a');
lines.push('// Builder Base building). Decoders must disambiguate by village.');
lines.push('');
lines.push('export const COC_HOME_BUILDING_IDS: Record<number, string> = {');
lines.push(emit(homeIds));
lines.push('};');
lines.push('');
lines.push('export const COC_BUILDER_BUILDING_IDS: Record<number, string> = {');
lines.push(emit(builderIds));
lines.push('};');
lines.push('');

writeFileSync(outPath, lines.join('\n'));
console.log(`Wrote ${outPath} (${homeIds.size} home + ${builderIds.size} builder IDs)`);
